### PR TITLE
Fix parsing ABIs with tuple[] in- or outputs

### PR DESCRIPTION
**Pull request by Jannis**
Part of fixing graphprotocol/graph-node#1800.

Right now, an ABI that contains a tuple array, like
```json
{
  "components": [
    { "type": "address" },
    { "type": "uint256" }
  ],
  "type": "tuple[]"
}
```
will parse this as `ParamType::Array(Box::new(ParamType::Tuple(vec![])))` rather than properly collecting the `components` types. This is because these are only collected if the type is `tuple`, not `tuple[]`. This PR fixes that and adds a few other tests related to reading and writing tuple array types.

### CODE REVIEW

**Review by fordN — CHANGES_REQUESTED** [review]
`tuple[]` deserializing looks good! Will we need to also make any changes to support encoding and decoding `tuple[]` type params?  I think it will work as is, but can we add a few tests to be sure?

**Comment by Jannis** [comment]
@fordN I've added a roundtrip test for tuple array encoding (inside a tuple, just to make sure it works in nested cases) and fixed the code formatting so that tests should now pass.

**Comment by fordN** [comment]
👍

**Review by fordN — APPROVED** [review]
👍

**Pull request merged**
